package views;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import models.Sales;
import models.SalesDao;
import models.SalesDetail;

/**
 *
 * @author Raul
 */
public class PrintSale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrintSale.class.getName());

    Sales sale = new Sales();
    SalesDao salesDao = new SalesDao();
    SalesDetail saleDetail = new SalesDetail();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form PrintSale
     */
    public PrintSale(int id) {
        initComponents();
        // Icono de la ventana (arriba a la izquierda)
        Image icon = new ImageIcon(getClass().getResource("/images/ferreteria_el_chalan_icon.png")).getImage();
        setIconImage(icon);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Factura de venta");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        txt_invoice_sale.setText("" + id);
        listAllSalesDetails(id);
        calculateSale();
    }

    public void listAllSalesDetails(int id){
        List<SalesDetail> list = salesDao.listSalesDetailQuery(id);
        model = (DefaultTableModel) sale_details_table.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getProduct_name();
            row[1] = list.get(i).getSale_quantity();
            row[2] = list.get(i).getSale_price();
            row[3] = list.get(i).getSale_subtotal();
            row[4] = list.get(i).getEmployee_name();
            row[5] = list.get(i).getCustomer_name();
            row[6] = list.get(i).getSale_date();
            model.addRow(row);
        }
        sale_details_table.setModel(model);
    }
    
    //Calcular el total
    public void calculateSale() {
        double total = 0.00;
        int numRow = sale_details_table.getRowCount();
        for (int i = 0; i < numRow; i++) {
            total = total + Double.parseDouble(String.valueOf(sale_details_table.getValueAt(i, 3)));
        }
        txt_total_sale.setText("" + total);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_print_sale = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_invoice_sale = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sale_details_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_total_sale = new javax.swing.JTextField();
        btn_print_sale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form_print_sale.setBackground(new java.awt.Color(255, 165, 10));
        form_print_sale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-factura.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        form_print_sale.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        jPanel1.setBackground(new java.awt.Color(18, 35, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FERRETERIA EL CHALAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txt_invoice_sale.setEditable(false);
        jPanel1.add(txt_invoice_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 20, 110, -1));

        form_print_sale.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Detalles de la venta");
        form_print_sale.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        sale_details_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal", "Vendedor", "Cliente", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sale_details_table);
        if (sale_details_table.getColumnModel().getColumnCount() > 0) {
            sale_details_table.getColumnModel().getColumn(0).setMinWidth(100);
            sale_details_table.getColumnModel().getColumn(5).setMinWidth(110);
            sale_details_table.getColumnModel().getColumn(6).setMinWidth(80);
        }

        form_print_sale.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 620, 310));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total :");
        form_print_sale.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));
        form_print_sale.add(txt_total_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 140, 30));

        getContentPane().add(form_print_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 520));

        btn_print_sale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_print_sale.setText("IMPRIMIR");
        btn_print_sale.addActionListener(this::btn_print_saleActionPerformed);
        getContentPane().add(btn_print_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_print_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_saleActionPerformed
        Toolkit tk = form_print_sale.getToolkit();
        PrintJob pj = tk.getPrintJob(this, null, null);
        Graphics graphics = pj.getGraphics();
        form_print_sale.print(graphics);
        graphics.dispose();
        pj.end();
    }//GEN-LAST:event_btn_print_saleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_print_sale;
    private javax.swing.JPanel form_print_sale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sale_details_table;
    private javax.swing.JTextField txt_invoice_sale;
    private javax.swing.JTextField txt_total_sale;
    // End of variables declaration//GEN-END:variables
}
